/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.partner;

import domen.Mesto;
import domen.PoslovniPartner;
import forme.partner.model.PoslovniPartnerTableModel;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import poslovnalogika.Kontroler;

/**
 *
 * @author student
 */
public class FrmUnosPartnera extends javax.swing.JDialog {

    /**
     * Creates new form FrmUnosPartnera
     */
    public FrmUnosPartnera(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtPartnerID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtNaziv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtPib = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtMaticniBroj = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtUlica = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtBroj = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jcbMesto = new javax.swing.JComboBox();
        jbtnSacuvaj = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblPartner = new javax.swing.JTable();
        jbtnDodajRed = new javax.swing.JButton();
        jbtnObrisiRed = new javax.swing.JButton();
        jbtnSacuvajListuPartnera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("PartnerID:");

        jLabel2.setText("Naziv:");

        jLabel3.setText("PIB:");

        jLabel4.setText("Matični broj:");

        jLabel5.setText("Ulica:");

        jLabel6.setText("Broj:");

        jLabel7.setText("Mesto:");

        jcbMesto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbtnSacuvaj.setText("Sačuvaj");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        jtblPartner.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblPartner);

        jbtnDodajRed.setText("+");
        jbtnDodajRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajRedActionPerformed(evt);
            }
        });

        jbtnObrisiRed.setText("-");
        jbtnObrisiRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiRedActionPerformed(evt);
            }
        });

        jbtnSacuvajListuPartnera.setText("Sačuvaj listu partnera");
        jbtnSacuvajListuPartnera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajListuPartneraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtNaziv)
                            .addComponent(jtxtPartnerID)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbMesto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtBroj)
                            .addComponent(jtxtUlica)
                            .addComponent(jtxtPib)
                            .addComponent(jtxtMaticniBroj, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnSacuvaj)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnDodajRed, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnObrisiRed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jbtnSacuvajListuPartnera))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtPartnerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtPib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtMaticniBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtUlica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcbMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnSacuvaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDodajRed)
                    .addComponent(jbtnObrisiRed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnSacuvajListuPartnera)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
        try {
            int partnerID = Integer.parseInt(jtxtPartnerID.getText().trim());
            String naziv = jtxtNaziv.getText().trim();
            String pib = jtxtPib.getText().trim();
            String maticniBroj = jtxtMaticniBroj.getText().trim();
            String ulica = jtxtUlica.getText().trim();
            String broj = jtxtBroj.getText().trim();
            Mesto m = (Mesto) jcbMesto.getSelectedItem();

            // TODO Validacija
            PoslovniPartner pp = new PoslovniPartner(partnerID, naziv, maticniBroj, pib, ulica, broj, m);
            Kontroler.getInstance().sacuvajPartnera(pp);
            JOptionPane.showMessageDialog(this, "Partner je sacuvan!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Partner nije sacuvan! " + ex.getMessage());
        }
    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    private void jbtnDodajRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajRedActionPerformed
        PoslovniPartnerTableModel model = (PoslovniPartnerTableModel) jtblPartner.getModel();
        model.dodajRed();
    }//GEN-LAST:event_jbtnDodajRedActionPerformed

    private void jbtnObrisiRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiRedActionPerformed
        int red = jtblPartner.getSelectedRow();
        if (red != -1) {
            PoslovniPartnerTableModel model = (PoslovniPartnerTableModel) jtblPartner.getModel();
            model.obrisiRed(red);
        } else {
            JOptionPane.showMessageDialog(this, "Morate odabrati red!");
        }
    }//GEN-LAST:event_jbtnObrisiRedActionPerformed

    private void jbtnSacuvajListuPartneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajListuPartneraActionPerformed
        PoslovniPartnerTableModel model = (PoslovniPartnerTableModel) jtblPartner.getModel();
        try {
            Kontroler.getInstance().sacuvajPartnere(model.vratiParntere());
            JOptionPane.showMessageDialog(this, "Lista partnera je sacuvana!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnSacuvajListuPartneraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUnosPartnera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUnosPartnera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUnosPartnera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUnosPartnera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmUnosPartnera dialog = new FrmUnosPartnera(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDodajRed;
    private javax.swing.JButton jbtnObrisiRed;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JButton jbtnSacuvajListuPartnera;
    private javax.swing.JComboBox jcbMesto;
    private javax.swing.JTable jtblPartner;
    private javax.swing.JTextField jtxtBroj;
    private javax.swing.JTextField jtxtMaticniBroj;
    private javax.swing.JTextField jtxtNaziv;
    private javax.swing.JTextField jtxtPartnerID;
    private javax.swing.JTextField jtxtPib;
    private javax.swing.JTextField jtxtUlica;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        List<Mesto> lm = Kontroler.getInstance().vratiMesta();
        jcbMesto.removeAllItems();
        JComboBox jcbMestoTabela = new JComboBox();
        jcbMestoTabela.removeAllItems();
        for (Mesto m : lm) {
            jcbMesto.addItem(m);
            jcbMestoTabela.addItem(m);
        }

        // Priprema tabele
        PoslovniPartnerTableModel model = new PoslovniPartnerTableModel(new LinkedList<>());
        jtblPartner.setModel(model);
        TableColumn tcMesto = jtblPartner.getColumnModel().getColumn(6);
        tcMesto.setCellEditor(new DefaultCellEditor(jcbMestoTabela));
    }
}
