/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.PoslovniPartner;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import komponente.tabela.model.ModelTabelePoslovniPartner;
import logic.Kontroler;

/**
 *
 * @author student
 */
public class FPretragaPoslovniPartner extends javax.swing.JDialog {

    /**
     * Creates new form FPretragaPoslovniPartner
     */
    public FPretragaPoslovniPartner(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        popuniTabeluPoslovniPartner();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblPoslovniPartner = new javax.swing.JTable();
        jbtnDetalji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pretraga poslovnih partnera");

        jtblPoslovniPartner.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PIB", "Maticni broj", "Naziv", "Adresa", "Sediste"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblPoslovniPartner);

        jbtnDetalji.setText("Detalji");
        jbtnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDetaljiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnDetalji)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jbtnDetalji)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDetaljiActionPerformed
        if (jtblPoslovniPartner.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Morate izabrati red u tabeli");
        } else {
            FPoslovniPartner formaZaUnos = new FPoslovniPartner(null, true);
            int index = jtblPoslovniPartner.getSelectedRow();
            PoslovniPartner p = Kontroler.getInstance().vratiPoslovnePartnere().get(index);
            formaZaUnos.postaviVrednostiPoljima(p);
            formaZaUnos.setTitle("Detalji poslovnog partnera");
            formaZaUnos.setVisible(true);
        }

    }//GEN-LAST:event_jbtnDetaljiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDetalji;
    private javax.swing.JTable jtblPoslovniPartner;
    // End of variables declaration//GEN-END:variables

    private void popuniTabeluPoslovniPartner() {
        List<PoslovniPartner> partneri = Kontroler.getInstance().vratiPoslovnePartnere();
//        TableModel tm = jtblPoslovniPartner.getModel();
//        DefaultTableModel dtm = (DefaultTableModel) tm;
//        Object[] podaci;
//        for (PoslovniPartner poslovniPartner : partneri) {
//            podaci = new Object[5];
//            podaci[0] = poslovniPartner.getPib();
//            podaci[1] = poslovniPartner.getMaticniBroj();
//            podaci[2] = poslovniPartner.getNaziv();
//            podaci[3] = poslovniPartner.getUlica() + " " + poslovniPartner.getBroj();
//            podaci[4] = poslovniPartner.getMesto();
//            dtm.addRow(podaci);
//        }
        TableModel tm = new ModelTabelePoslovniPartner(partneri);
        jtblPoslovniPartner.setModel(tm);

    }
}
