/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Mesto;
import domen.PoslovniPartner;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import komponente.tabela.model.ModelTabelePoslovniPartnerUnos;
import logic.Kontroler;

/**
 *
 * @author student
 */
public class JPanelUnosPoslovnihPartneraTabelarno extends javax.swing.JPanel {

    /**
     * Creates new form JPanelUnosPoslovnihPartneraTabelarno
     */
    public JPanelUnosPoslovnihPartneraTabelarno() {
        initComponents();
        pripremitabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePoslovniPartneri = new javax.swing.JTable();
        jButtonDodajPoslovnogPartnera = new javax.swing.JButton();
        jButtonObrisiPoslovnogPartnera = new javax.swing.JButton();
        jButtonSacuvaj = new javax.swing.JButton();

        jTablePoslovniPartneri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePoslovniPartneri);

        jButtonDodajPoslovnogPartnera.setText("+");
        jButtonDodajPoslovnogPartnera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajPoslovnogPartneraActionPerformed(evt);
            }
        });

        jButtonObrisiPoslovnogPartnera.setText("-");
        jButtonObrisiPoslovnogPartnera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiPoslovnogPartneraActionPerformed(evt);
            }
        });

        jButtonSacuvaj.setText("Sacuvaj");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSacuvaj))
                    .addComponent(jButtonObrisiPoslovnogPartnera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDodajPoslovnogPartnera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonDodajPoslovnogPartnera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonObrisiPoslovnogPartnera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSacuvaj))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDodajPoslovnogPartneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajPoslovnogPartneraActionPerformed
        ModelTabelePoslovniPartnerUnos tm=(ModelTabelePoslovniPartnerUnos)jTablePoslovniPartneri.getModel();
        tm.dodajPoslovnogPartnera(new PoslovniPartner());
    }//GEN-LAST:event_jButtonDodajPoslovnogPartneraActionPerformed

    private void jButtonObrisiPoslovnogPartneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiPoslovnogPartneraActionPerformed
        ModelTabelePoslovniPartnerUnos tm=(ModelTabelePoslovniPartnerUnos)jTablePoslovniPartneri.getModel();
        //provjeriti da li je ista selektovano!!!
        tm.obrisiPoslovnogPartnera(jTablePoslovniPartneri.getSelectedRow());
    }//GEN-LAST:event_jButtonObrisiPoslovnogPartneraActionPerformed

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
        ModelTabelePoslovniPartnerUnos tm=(ModelTabelePoslovniPartnerUnos)jTablePoslovniPartneri.getModel();
        List<PoslovniPartner> partneri=tm.vratiListuPoslovnihPartnera();
        try{
            Kontroler.getInstance().sacuvajPoslovnePartnere(partneri);
            JOptionPane.showMessageDialog(this, "Uspesno sacuvani poslovni partneri!", "Cuvanje partnera", JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Poslovni partneri nisu sacuvani!\n"+e.getMessage(), "Cuvanje partnera", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSacuvajActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajPoslovnogPartnera;
    private javax.swing.JButton jButtonObrisiPoslovnogPartnera;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePoslovniPartneri;
    // End of variables declaration//GEN-END:variables

private void pripremitabelu(){
    List<PoslovniPartner> partneri=new ArrayList<>();
    ModelTabelePoslovniPartnerUnos tm=new ModelTabelePoslovniPartnerUnos(partneri);
    jTablePoslovniPartneri.setModel(tm);
    
    List<Mesto> mesta=Kontroler.getInstance().vratiMesta();
    JComboBox jcbMesta=new JComboBox(mesta.toArray());
    TableColumnModel tcm=jTablePoslovniPartneri.getColumnModel();
    TableColumn tc=tcm.getColumn(5);
    tc.setCellEditor(new DefaultCellEditor(jcbMesta));
    
}



}
