/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.partner;

import domen.PoslovniPartner;
import forme.partner.model.PoslovniPartnerTableModel;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import poslovnalogika.Kontroler;

/**
 *
 * @author student
 */
public class FrmPrikazPartneraTabela extends javax.swing.JPanel {

    /**
     * Creates new form FrmPrikazPartneraTabela
     */
    public FrmPrikazPartneraTabela() {
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblPartner = new javax.swing.JTable();
        jbtnDetalji = new javax.swing.JButton();

        jtblPartner.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PartnerID", "Naziv", "PIB", "Matični broj", "Ulica", "Broj", "Mesto"
            }
        ));
        jScrollPane1.setViewportView(jtblPartner);

        jbtnDetalji.setText("Detalji");
        jbtnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDetaljiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtnDetalji))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnDetalji)
                .addGap(0, 11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDetaljiActionPerformed
        int red = jtblPartner.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Niste odabrali partnera!");
        } else {
            PoslovniPartnerTableModel model = (PoslovniPartnerTableModel) jtblPartner.getModel();
            PoslovniPartner pp = model.vratiPartnera(red);
            JOptionPane.showMessageDialog(this, "Izabran partner: " + pp.getNaziv());
        }
    }//GEN-LAST:event_jbtnDetaljiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDetalji;
    private javax.swing.JTable jtblPartner;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        List<PoslovniPartner> lp = Kontroler.getInstance().vratiPartnere();
//        DefaultTableModel model = (DefaultTableModel) jtblPartner.getModel();
//        Object[] red;
//        for (PoslovniPartner pp : lp) {
//            red = new Object[7];
//            red[0] = pp.getPartnerID();
//            red[1] = pp.getNaziv();
//            red[2] = pp.getPib();
//            red[3] = pp.getMaticniBroj();
//            red[4] = pp.getUlica();
//            red[5] = pp.getBroj();
//            red[6] = pp.getMesto();
//            model.addRow(red);
//        }
        PoslovniPartnerTableModel model = new PoslovniPartnerTableModel(lp);
        jtblPartner.setModel(model);
    }
}
