/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import conroller.Controller;
import domen.Angazovanje;
import domen.Gradiliste;
import domen.Radnik;
import exception.ValidacijaException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.AngazovanjeTableModel;

/**
 *
 * @author elezs
 */
public class UnosAngazovanjaForm extends javax.swing.JFrame {

    /**
     * Creates new form UnosAngazovanjaForm
     */
    List<Angazovanje> angazovanja;

    public UnosAngazovanjaForm() {
        angazovanja = new ArrayList<>();
        initComponents();
        postaviComboBoxGradiliste();
        postaviComboBoxRadnik();
        srediTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabelGradiliste = new javax.swing.JLabel();
        jLabelRadnik = new javax.swing.JLabel();
        jLabelSati = new javax.swing.JLabel();
        jLabelDatum = new javax.swing.JLabel();
        jComboBoxGradiliste = new javax.swing.JComboBox<>();
        jComboBoxRadnik = new javax.swing.JComboBox<>();
        jTextFieldSati = new javax.swing.JTextField();
        jTextFieldDatum = new javax.swing.JTextField();
        jButtonDodaj = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableAngazovanja = new javax.swing.JTable();
        jButtonSacuvaj = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[FON]Unos angazovanja");

        jLabelGradiliste.setText("Gradiliste:");

        jLabelRadnik.setText("Radnik:");

        jLabelSati.setText("Broj sati:");

        jLabelDatum.setText("Datum(dd.MM.yyyy):");

        jButtonDodaj.setText("Dodaj angazovanje");
        jButtonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajActionPerformed(evt);
            }
        });

        jButtonObrisi.setText("Obrisi angazovanje");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        jTableAngazovanja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableAngazovanja);

        jButtonSacuvaj.setText("Sacuvaj angazovanje");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDatum)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldDatum))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelGradiliste)
                                    .addComponent(jLabelRadnik)
                                    .addComponent(jLabelSati))
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxGradiliste, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxRadnik, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldSati)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 150, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGradiliste)
                    .addComponent(jComboBoxGradiliste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRadnik)
                    .addComponent(jComboBoxRadnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSati)
                    .addComponent(jTextFieldSati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDatum)
                    .addComponent(jTextFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDodaj)
                    .addComponent(jButtonObrisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSacuvaj)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajActionPerformed
        try {
            //Controller.instanceController().dodajPolje();
            AngazovanjeTableModel atm = (AngazovanjeTableModel) jTableAngazovanja.getModel();
            Gradiliste gr = (Gradiliste) jComboBoxGradiliste.getSelectedItem();
            Radnik r = (Radnik) jComboBoxRadnik.getSelectedItem();
            String brSati = jTextFieldSati.getText();
            String datum = jTextFieldDatum.getText();
            Angazovanje a = kreirajAngazovanje(brSati, datum, r, gr);
            atm.dodajNoviRed(a);
        } catch (ValidacijaException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDodajActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        int red = jTableAngazovanja.getSelectedRow();
        //Controller.instanceController().obrisiPolje(red);

        if (red == -1) {
            JOptionPane.showMessageDialog(rootPane, "Izaberite angazovanje koje zelite da obrisete", "Upozorenje", JOptionPane.WARNING_MESSAGE);
        } else {
            AngazovanjeTableModel atm = (AngazovanjeTableModel) jTableAngazovanja.getModel();
            atm.obrisiRed(red);
        }

    }//GEN-LAST:event_jButtonObrisiActionPerformed

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
        AngazovanjeTableModel atm = (AngazovanjeTableModel) jTableAngazovanja.getModel();
        angazovanja = atm.vratiListuAngazovanja();
        boolean uspesno = false;
        
        uspesno = Controller.instanceController().sacuvajAngazovanja(angazovanja);
        if(uspesno ){
            JOptionPane.showMessageDialog(rootPane, "Angazovanja uspesno sacuvana!");
            ocistiPolja();
            srediFormu();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Doslo je do greske prilikom cuvanja angazovanja!");
        }
    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnosAngazovanjaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnosAngazovanjaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnosAngazovanjaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnosAngazovanjaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnosAngazovanjaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JComboBox<Gradiliste> jComboBoxGradiliste;
    private javax.swing.JComboBox<Radnik> jComboBoxRadnik;
    private javax.swing.JLabel jLabelDatum;
    private javax.swing.JLabel jLabelGradiliste;
    private javax.swing.JLabel jLabelRadnik;
    private javax.swing.JLabel jLabelSati;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableAngazovanja;
    private javax.swing.JTextField jTextFieldDatum;
    private javax.swing.JTextField jTextFieldSati;
    // End of variables declaration//GEN-END:variables

    private void postaviComboBoxGradiliste() {
        jComboBoxGradiliste.removeAllItems();
        List<Gradiliste> gradilista = Controller.instanceController().vratiGradilista();
        for (Gradiliste g : gradilista) {
            jComboBoxGradiliste.addItem(g);
        }
    }

    private void postaviComboBoxRadnik() {
        jComboBoxRadnik.removeAllItems();
        List<Radnik> radnici = Controller.instanceController().vratiRadnike();
        for (Radnik r : radnici) {
            jComboBoxRadnik.addItem(r);
        }
    }

    private void srediTabelu() {
        //List<Angazovanje> angazovanja = Controller.instanceController().vratiAngazovanja();
        jTableAngazovanja.setModel(new AngazovanjeTableModel());
    }

    private Angazovanje kreirajAngazovanje(String brSati, String datum, Radnik r, Gradiliste gr) throws ValidacijaException {
        if (brSati == null && datum == null) {
            throw new ValidacijaException("Morate popuniti sva polja");
        }
        int sati;
        try {
            sati = Integer.parseInt(brSati);
        } catch (Exception e) {
            throw new ValidacijaException("Morate uneti broj sati kao ceo broj");
        }
        SimpleDateFormat sdf = new SimpleDateFormat("dd.mm.yyyy");
        Date dat;
        try {
            dat = sdf.parse(datum);
        } catch (ParseException ex) {
            throw new ValidacijaException("Datum morate uneti u formatu dd.MM.yyyy");
        }
        return new Angazovanje(-1, sati, dat, r, gr);
    }

    private void srediFormu() {
        AngazovanjeTableModel atm = new AngazovanjeTableModel();
        jTableAngazovanja.setModel(atm);
    }

    private void ocistiPolja() {
        jTextFieldDatum.setText("");
        jTextFieldSati.setText("");
        jComboBoxRadnik.setSelectedIndex(0);
        jComboBoxGradiliste.setSelectedIndex(0);
    }
}
