/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Angazovanje;
import domen.Gradiliste;
import domen.Radnik;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logika.Kontroler;
import modeltabele.ModelTabeleAngazovanja;

/**
 *
 * @author Miroslav
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
        srediKomboRadnika();
        srediKomboGradilista();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbRadnik = new javax.swing.JComboBox();
        cmbGradiliste = new javax.swing.JComboBox();
        txtSati = new javax.swing.JTextField();
        txtDatum = new javax.swing.JTextField();
        btnDodaj = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAngozovanje = new javax.swing.JTable();
        btnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Radnik");

        jLabel2.setText("Gradiliste");

        jLabel3.setText("broj sati");

        jLabel4.setText("datum");

        cmbRadnik.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbGradiliste.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbGradiliste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGradilisteActionPerformed(evt);
            }
        });

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        tabelaAngozovanje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaAngozovanje);

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbGradiliste, 0, 426, Short.MAX_VALUE)
                                .addComponent(cmbRadnik, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDatum, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                                .addComponent(txtSati)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnDodaj)
                            .addGap(18, 18, 18)
                            .addComponent(btnObrisi))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                    .addComponent(btnSacuvaj))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbRadnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbGradiliste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnObrisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSacuvaj)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbGradilisteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGradilisteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGradilisteActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        
        Radnik r = (Radnik) cmbRadnik.getSelectedItem();
        Gradiliste g = (Gradiliste) cmbGradiliste.getSelectedItem();
        
        String brS = txtSati.getText();
        String dat = txtDatum.getText();
        if(brS.isEmpty() || dat.isEmpty()){
            JOptionPane.showMessageDialog(this, "Sva polja su ovacezna");
            return;
        }
        
        int brojSati = Integer.parseInt(brS);
        
       
        
        
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        Date datum = null;
        try {
            datum = sdf.parse(dat);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Nije dobar format. treba da bude dd.MM.yyyy");
            return;
        }
        
        Angazovanje a = new Angazovanje(-1, brojSati, datum, r, g);
        
        ModelTabeleAngazovanja mta = (ModelTabeleAngazovanja) tabelaAngozovanje.getModel();
        mta.dodaj(a);
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        int red = tabelaAngozovanje.getSelectedRow();
        
        if(red == -1){
            JOptionPane.showMessageDialog(this, "Niste izabrali red", "Upozorenje", JOptionPane.WARNING_MESSAGE);
        }else{
            ModelTabeleAngazovanja mta = (ModelTabeleAngazovanja) tabelaAngozovanje.getModel();
            mta.obrisi(red);
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        
        ModelTabeleAngazovanja mta = (ModelTabeleAngazovanja) tabelaAngozovanje.getModel();
        ArrayList<Angazovanje> lista = mta.getLista();
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        
        for (int i = 0; i < lista.size(); i++) {
            String dat1 = sdf.format(lista.get(i).getDatum());
            int ukupnoSati = lista.get(i).getBrojSati();
            for (int j = i+1; j < lista.size(); j++) {
                String dat2 = sdf.format(lista.get(j).getDatum());
                
                if(lista.get(i).getRadnik().getRadnikID()== lista.get(j).getRadnik().getRadnikID() && dat1.equals(dat2)){
                    if(lista.get(i).getGradiliste().getGradilisteID()!=lista.get(j).getGradiliste().getGradilisteID()){
                        JOptionPane.showMessageDialog(this, "Gradiliste mora biti isto u istom danu", "greska", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    ukupnoSati+=lista.get(j).getBrojSati();
                }
            }
            
            if(ukupnoSati>8){
                JOptionPane.showMessageDialog(this, "Vise od 8 sati", "greska", JOptionPane.ERROR_MESSAGE);
                        return;
            }
        }
        
        boolean sacuvano = Kontroler.getInstanca().sacuvajSvaAngazovanja(lista);
        
        
        if(sacuvano){
            JOptionPane.showMessageDialog(this, "Sve uspesno sacuvano", "uspeh", JOptionPane.INFORMATION_MESSAGE);       
        }else{
            JOptionPane.showMessageDialog(this, "Sjebao si nesto", "greska", JOptionPane.ERROR_MESSAGE);       
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbGradiliste;
    private javax.swing.JComboBox cmbRadnik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaAngozovanje;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtSati;
    // End of variables declaration//GEN-END:variables

    private void srediKomboRadnika() {
        
        cmbRadnik.removeAllItems();
        
        ArrayList<Radnik> listaRadnika = Kontroler.getInstanca().vratiListuRadnika();
        
        for (Radnik radnik : listaRadnika) {
            cmbRadnik.addItem(radnik);
        }
    }

    private void srediKomboGradilista() {
        cmbGradiliste.removeAllItems();
        
        ArrayList<Gradiliste> lista = Kontroler.getInstanca().vratiGradilista();
        
        for (Gradiliste gradiliste : lista) {
            cmbGradiliste.addItem(gradiliste);
        }

    }

    private void srediFormu() {
        ModelTabeleAngazovanja mta = new ModelTabeleAngazovanja();
        tabelaAngozovanje.setModel(mta);
    }
}
