/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Predmet;
import domen.Prijava;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import model.ModelTabelePrijava;

/**
 *
 * @author Cule
 */
public class GlavnaEkranskaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaEkranskaForma
     */
    public GlavnaEkranskaForma() {
        initComponents();
        popuniKomboPredmeta();
        popuniTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcmbPredmeti = new javax.swing.JComboBox();
        jbtnPonistiFilter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblPrikaz = new javax.swing.JTable();
        jbtnDodajVrednost = new javax.swing.JButton();
        jbtnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Filter"));

        jLabel1.setText("Predmet:");

        jcmbPredmeti.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcmbPredmeti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbPredmetiActionPerformed(evt);
            }
        });

        jbtnPonistiFilter.setText("Ponisti filter");
        jbtnPonistiFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPonistiFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jcmbPredmeti, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jbtnPonistiFilter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcmbPredmeti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPonistiFilter))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jtblPrikaz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblPrikaz);

        jbtnDodajVrednost.setText("Dodaj polozio");
        jbtnDodajVrednost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajVrednostActionPerformed(evt);
            }
        });

        jbtnSacuvaj.setText("Sacuvaj");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnDodajVrednost, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnDodajVrednost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnSacuvaj))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcmbPredmetiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbPredmetiActionPerformed
        popuniTabelu();
    }//GEN-LAST:event_jcmbPredmetiActionPerformed

    private void jbtnDodajVrednostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajVrednostActionPerformed
        DodajPolozio dp = new DodajPolozio(this);
        dp.setVisible(true);
    }//GEN-LAST:event_jbtnDodajVrednostActionPerformed

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
        ArrayList<Prijava> lista = Kontroler.getInstance().vratiPrijaveIzKolekcije();
        
        boolean sacuvano = Kontroler.getInstance().sacuvajSveeeee(lista);
        
        if(sacuvano){
            JOptionPane.showMessageDialog(this, "Sve je dobro sacuvano");
        }else{
            JOptionPane.showMessageDialog(this, "Sve je lose sacuvano");
        }
    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    private void jbtnPonistiFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPonistiFilterActionPerformed
        jcmbPredmeti.setSelectedIndex(0);
        Kontroler.getInstance().popuniKolekcijuPrijava();
        popuniTabelu();
    }//GEN-LAST:event_jbtnPonistiFilterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaEkranskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaEkranskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaEkranskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaEkranskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaEkranskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDodajVrednost;
    private javax.swing.JButton jbtnPonistiFilter;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JComboBox jcmbPredmeti;
    private javax.swing.JTable jtblPrikaz;
    // End of variables declaration//GEN-END:variables

    private void popuniKomboPredmeta() {

        jcmbPredmeti.removeAllItems();
        jcmbPredmeti.addItem(new Predmet(-1, "Svi predmeti"));
        for (Predmet p : Kontroler.getInstance().vratiListuPredmetaIzKolekcije()) {
            jcmbPredmeti.addItem(p);
        }
    }

    public void popuniTabelu() {
        ArrayList<Prijava> lista = Kontroler.getInstance().vratiPrijaveIzKolekcije();
        Predmet p = (Predmet) jcmbPredmeti.getSelectedItem();
        //jedan nacin rada, filtriranje u kodu, bez koriscenja baze
        ArrayList<Prijava> listaPrijavaFiltrirana = new ArrayList<>();
        //stavili smo da je minus 1 onaj svi predmeti
        if(p==null || p.getSifraPredmeta()==-1){
            listaPrijavaFiltrirana=lista;
        }else{
            for (Prijava pr : lista) {
                if(pr.getPredmet().getNaziv().equals(p.getNaziv())){
                    listaPrijavaFiltrirana.add(pr);
                }
            }
        }
        
        ModelTabelePrijava mtp = new ModelTabelePrijava(listaPrijavaFiltrirana);
        jtblPrikaz.setModel(mtp);
    }
}
