/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import domen.Zadatak;
import domen.Zaposleni;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.ZadatakTableModel;

/**
 *
 * @author elezs
 */
public class FrmNoviZadatak extends javax.swing.JDialog {

    /**
     * Creates new form FrmNoviZadatak
     */
    public FrmNoviZadatak(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ucitajZaposlene();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNaziv = new javax.swing.JTextField();
        jTextFieldDatum = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxZaposleni = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonSacuvaj = new javax.swing.JButton();
        jButtonOdustani = new javax.swing.JButton();
        jTextFieldSifraZ = new javax.swing.JTextField();
        jTextFieldOpis = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Sifra:");

        jComboBoxZaposleni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxZaposleniActionPerformed(evt);
            }
        });

        jLabel2.setText("Opis:");

        jLabel3.setText("Naziv:");

        jLabel4.setText("Datuma:");

        jLabel5.setText("Zaposleni:");

        jButtonSacuvaj.setText("Sacuvaj");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });

        jButtonOdustani.setText("Odustani");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jButtonSacuvaj)
                            .addComponent(jButtonOdustani))))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(jTextFieldSifraZ)
                    .addComponent(jTextFieldOpis, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(jTextFieldDatum, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(jComboBoxZaposleni, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldSifraZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addComponent(jTextFieldOpis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonSacuvaj)
                .addGap(18, 18, 18)
                .addComponent(jButtonOdustani)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
        // TODO add your handling code here:
        Zadatak zadatak = kreirajZadatak();
        GlavnaForma gf = (GlavnaForma) this.getParent();
        ZadatakTableModel ztm = gf.getModel();
        ztm.sacuvajZadatak(zadatak);
        //GlavnaForma.kreirajFormu().ubaciUTabelu(zadatak);

        //Controller.getInstance().prihvatiZadatak(zadatak);
        //ZadatakTableModel ztm = new ZadatakTableModel();
        //ztm.sacuvajZadatak(zadatak);
    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        // TODO add your handling code here:
        //NoviZadatak nz = new NoviZadatak();
        //nz.dispatchEvent(new WindowEvent(nz, WindowEvent.WINDOW_CLOSING));
        dispose();
    }//GEN-LAST:event_jButtonOdustaniActionPerformed

    private void jComboBoxZaposleniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxZaposleniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxZaposleniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNoviZadatak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNoviZadatak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNoviZadatak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNoviZadatak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmNoviZadatak dialog = new FrmNoviZadatak(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JComboBox<Zaposleni> jComboBoxZaposleni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldDatum;
    private javax.swing.JTextField jTextFieldNaziv;
    private javax.swing.JTextField jTextFieldOpis;
    private javax.swing.JTextField jTextFieldSifraZ;
    // End of variables declaration//GEN-END:variables

    private Zadatak kreirajZadatak() {
        Zadatak z;
        if (jTextFieldSifraZ.getText().isEmpty() || jTextFieldOpis.getText().isEmpty() || jTextFieldNaziv.getText().isEmpty() || jTextFieldDatum.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Sva polja su obavezna", "Greska", JOptionPane.WARNING_MESSAGE);
        } else {
            /*if(!jTextFieldSifraZ.getText().matches("SIF-*")){
                JOptionPane.showMessageDialog(rootPane, "Sifru unesite u formatu SIF-broj", "Greska", JOptionPane.WARNING_MESSAGE);
            }*/
            try {
                z = new Zadatak();
                z.setSifraZadatka(jTextFieldSifraZ.getText());
                z.setOpis(jTextFieldOpis.getText());
                z.setNaziv(jTextFieldNaziv.getText());
                String d = jTextFieldDatum.getText();
                SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
                java.util.Date utilDate = sdf.parse(d);
                Date datum = new Date(utilDate.getTime());
                z.setDatum(datum);
                z.setZaposleni((Zaposleni) jComboBoxZaposleni.getSelectedItem());
                dispose();
                System.out.println(z.getSifraZadatka());
                return z;

            } catch (ParseException ex) {
                Logger.getLogger(FrmNoviZadatak.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        System.out.println("Zadatak nije kreiran");
        return null;
    }

    private void ucitajZaposlene() {
        List<Zaposleni> zaposleni;
        zaposleni = Controller.getInstance().vratiZaposlene();
        for (Zaposleni z : zaposleni) {
            jComboBoxZaposleni.addItem(z);
        }
    }
}
